### ISSUE TITLE
@SameLen not a two way relation

### ISSUE THREAD

**Issue by mstaehely** [kelloggm/checker-framework#101]
The following code generates a warning, and we are not sure if this is intended behavior or not:

```
    public static void reflect() {
        int size = 5;
        int[] a = new int[size];
        int[] b = new int @SameLen("a") [size];

        // Works fine, and should work.
        for (int i = 0; i < a.length; i++) {
            a[i] = i;
            b[i] = i;
        }

        // Does not work. Issues unsafe high access warning,
        // found    : @LTLengthOf("b") int
        // required: an integer less than a's length (@LTLengthOf("a"))
        for (int j = 0; j < b.length; j++) {
            a[j] = j;
            b[j] = j;
        }
    }
```

**Comment by kelloggm** [comment]
The `@SameLen` annotation is in the wrong place. If line 4 is rewritten like this, `int @SameLen("a") [] b = new int [size];`, then the SameLen Checker issues an assignment incompatible error on line 4: it can't prove that a and b have the same length. This is the same problem I described #99.

**Comment by kelloggm** [comment]
That said, the issue you're actually talking about here also appears to be a real bug in the SameLen Checker; the relationship ought to be symmetric but isn't.

**Comment by kelloggm** [comment]
I've looked into this further. The fundamental problem is that when a programmer writes annotations, they aren't automatically symmetric. Here's a smaller test case that showcases the problem:

```java
    void test(int @SameLen("#2") [] a, int[] b) {
	int[] c = new int[a.length];
	for(int i = 0; i < c.length; i++) { // i's type is @LTL("c")
	    b[i] = 1; // b's type is @SameLenUnknown, so fails
	    int @SameLen({"a", "b", "c"}) [] d = c; // succeeds
	}
    }
```

SameLen types are symmetric in the sense that all the ones that are inferred are applied to both of the arrays involved. So for instance in the example above, `int [] c = new int[a.length]` results in both a and c being updated. But it doesn't update the other SameLen types that are associated with a and c - which is to say, while both a and c become `@SameLen({"a","b","c"})`, the type of `b` never changes.

**Comment by kelloggm** [comment]
I've submitted a PR that addresses part of this problem, but fundamentally I think the annotation in the given test case isn't correct. If you only write an annotation on `a`, I'm not sure that you should expect there to automagically be a corresponding annotation on `b`. typetools#1056, however, does address what I see as the real problem with SameLen: SameLen wasn't updating every array in the list when new information was learned; it was only updating the arrays actually involved in the expression that resulted in new information being learned.

**Comment by kelloggm** [comment]
Closing because typetools#1056 has been merged.
