### ISSUE TITLE
Index JDK annotations need to be updated to take offset support into account.

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#103]
Running plume-lib like this produces a mountain of warnings because of incompatibility between the annotations and the new types. In particular, offsets are used quite a bit in the JDK, and right now they're all annotated as `@IndexOrHigh` instead of as offset variables.

**Comment by mernst** [comment]
Isn't `@IndexOrHigh` a type alias or synonym for an offset variable?
If so, I would think that the annotated JDK only has to be changed where `@IndexOrHigh` is insufficiently precise.

**Comment by kelloggm** [comment]
In this issue I'm referring to situations where it is insufficiently precise. While `@IndexOrHigh` was the most specific thing I could express while annotating before offsets were implemented, I can do a better job now. That's what this issue is about.

**Comment by kelloggm** [comment]
Closing this in favor of #144, which does not include incorrect claims about the number of warnings due to this.
