### ISSUE TITLE
New annotation: LTLengthOfOrZero

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#105]
Some methods in the JDK, like `System.arrayCopy`, take an index and the length of an array. If the length is zero, then the index is never used. This means that zero is always permissible in these situations: if the array has length 0, the index isn't used (so it's safe), and if the array has non-zero length, then 0 is always a valid index.

I propose adding a new type to the UBC to handle this kind of pattern, called LTLengthOfOrZero (LTOZ). LTOZ's semantics are identical to those of LTLengthOf _except_ when the Value Checker can prove that a value is zero, in which case it's always permissible to assign 0 into an LTOZ.

LTOZ is the supertype of LTLengthOf, and is a subtype of LTEqLengthOf, because the MinLen of all arrays is at least zero, so LTOZ is permitted anywhere LTEqLengthOf would be, for an individual array.

Integrating this type with offsets will be tricky. My best plan for doing so is to add a flag to each UBQualifier that says if it is permitted to be zero. Then, the UBQualifier representing a `LTOZ("a")` will be a `LessThanLength(value="a", offset="0", zero=true)`. I would appreciate feedback from both of you on this proposal.

**Comment by smillst** [comment]
Can you give an example?  Which parameter of arraycopy would have this new annotation?

**Comment by kelloggm** [comment]
The signature should be:

```java
    public static native void arraycopy(Object src,  @IndexFor("#1") int  srcPos,
                                        Object dest, @IndexOrZero("#3") int destPos,
                                        @IndexOrZero({"#1", "#3"}) int length);
```

`@IndexOrZero` should desugar into `@NonNegative @LTLengthOfOrZero`

**Comment by mernst** [comment]
I like Suzanne's second suggestion, which matches the documentation nicely and prevents more errors than the `@IndexOrZero` proposal.  Nice!
This should make it possible to annotate clients of `System.arrayCopy`, such as `ArraysMDE.subarray`.

**Comment by kelloggm** [comment]
I agree that Suzanne's suggestion is better than what I proposed. I'll try that out and see how things go on plume-lib.

**Comment by smillst** [comment]
I would guess you'll run into some uses of arraycopy that can type-check with the first signature but not the second and vice versa.  We may need to a precondition annotation for this (as mentioned in #75).  

````
@MustBeLTLengthOf(expr = {"#2 + #5 - 1", "#4 + #5 - 1"}, array {"#1", "#3"}) 
void arraycopy(Object src,   @NonNegative int  srcPos, 
               Object dest,  @NonNegative int destPos, @NonNegative int length);
````

**Comment by kelloggm** [comment]
Using Suzanne's first suggestion, there are now 82 warnings on plume-lib, a reduction of 58 from the last time I ran it. This is a HUGE improvement, so I think this is the right approach.

**Comment by kelloggm** [comment]
There are for sure still a lot of false positives, though. Most of them look like this:

```java
src/plume/ArraysMDE.java:1097: warning: [argument.type.incompatible] incompatible types in argument.
    System.arraycopy(a, startindex, result, 0, length);
                                               ^
  found   : @LTEqLengthOf({"a", "result"}) int
  required: @LTLengthOf(value={"a", "result"}, offset={"startindex - 1", "0 - 1"}) int
```
The type it found is pretty reasonable, and matches what's needed for the second part (i.e. the offset from `result` if the `0 - 1` is simplified. But the `startindex - 1` part (i.e. the offset from `a`) isn't inferred pretty much ever, as far as I can tell.

**Comment by smillst** [comment]
Are you sure this is a false positive? I think the annotation on length should be `@LTLengthOf(value = "#1", offset = "#2 -1")`  instead of `@IndexOrHigh(#1)` .

**Comment by kelloggm** [comment]
I think you're correct; I'm actually testing that right now because I'd come to the same conclusion. Sorry for the live-commenting; I'll try to limit myself to only saying things that are definitely true.

**Comment by kelloggm** [comment]
Changing the annotation does remove the warning, so that's the correct annotation for the method. I'll submit a pull-request to change the annotation on System.arraycopy, and when that's accepted we can close this issue.

**Comment by mernst** [comment]
You tried Suzanne's first annotation suggestion, and it helped a lot.
Did you also try Suzanne's second annotation suggestion?  I find it easier to read, but maybe the first one is better for some reason.

**Comment by kelloggm** [comment]
I've also tried out the second version. While I agree that it's somewhat more intuitive, it doesn't address the problem in a way I consider satisfactory. Even with the most precise possible annotations, the checker still issues a warning on the `0` constant when calling `arraycopy` in this example:

```java
//From ArraysMDE.java, starting at line 1094
  public static /*@PolyAll*/ Object[] subarray(
      /*@PolyAll*/ Object[] a, /*@NonNegative @LTLengthOf(value="#1", offset="#3 - 1")*/ int startindex, 
/*@NonNegative @LTLengthOf(value="#1", offset="#2 - 1")*/ int length) {
    /*@PolyAll*/ Object[] result = new /*@PolyAll*/ Object[length];
    System.arraycopy(a, startindex, result, 0, length);
    return result;
  }

// The resulting warning:
src/plume/ArraysMDE.java:1097: warning: [argument.type.incompatible] incompatible types in argument.
    System.arraycopy(a, startindex, result, 0, length);
                                            ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf(value="result", offset="length - 1") int
```

If `arraycopy` requires an upper bound type for the indexes, there's just no way to allow literal zero unless we also require that the array have a particular MinLen, since that's the only way to give a literal integer an upperbound type. So, I prefer the first version of the annotations that Suzanne suggested.

**Comment by kelloggm** [comment]
typetools#1076 merged Suzanne's first suggestion for the System.arraycopy annotation
