### ISSUE TITLE
Offset false positive

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#108]
Consider the following code:

```java
      double[] f1 = new double[10];
      double[] f2 = new double[20];

      for (int j = 0; j < f2.length; j++) {
        f2[j] = j;
      }
      for (int i = 0; i < f2.length - f1.length; i++) {

        //fill up f1 with elements of f2
        for (int j = 0; j < f1.length; j++) {
          f1[j] = f2[i + j]; // Index checker warns here
        }
}
```

This code produces the following warning:

```
src/plume/TestPlume.java:538: warning: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
          f1[j] = f2[i + j];
                       ^
  found   : @LTLengthOf(value={"f1", "f2"}, offset={"-i", "-j + 10"}) int
  required: an integer less than f2's length (@LTLengthOf("f2"))
```

I think that the UBC with offsets ought to be able to solve this case. I'm not sure why it can't.

**Comment by smillst** [comment]
2 Issues here:

1. If an expression has a know value, like 10 in the above error message, then both the know value, '10' and the expression, `f1.length` should be used as offsets.  In other words, the type of `i` should be `@LTLength(value = {"f2", "f2", "f2"}, offset = {"0", "10", "f1.length"})`

2. The UBC doesn't recognize that if an offset is an array length access, that any expression less than or equal to the length of that array is also an offset.  We need to add a refinement rule like:
If expression `i` has type `@LTLengthOf(value = "f2", offset = "f1.length") int` and expression `j` is less than or equal to  the length of `f1`, then the type of `i + j` is `@LTLengthOf("f2")`.
