### ISSUE TITLE
MinLen(4)?

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#112]
```java
class MinLenFourShenanigans {
  public static boolean isInterned(Object value) {
    if (value == null) {
      // nothing to do
      return true;
    } else if (value instanceof String) {
      return (value == ((String) value).intern());
    }
    return false;
  }

  public static boolean isInterned2(Object value) {
    if (value instanceof String) {
      return (value == ((String) value).intern());
    }
    return false;
  }
}
```

The code above emits the following warning. I have no idea why. `grep -R "@MinLen(4)" *` run in both the plume-lib source directory and the index jdk produces no results, so I don't know where the annotation could even be originating. Somehow, only the first version of the function causes the strange warning.

```java
javac -processor index MinLenFourShenanigans.java 
MinLenFourShenanigans.java:7: warning: [cast.unsafe] "@MinLen(0) Object" may not be casted to the type "@MinLen(4) String"
      return (value == ((String) value).intern());
                        ^
1 warning
```

**Comment by smillst** [comment]
`null` is annotated with `@StringVal("null")` by the Value Checker, which would be converted to `@MinLen(4)`.  That's where the `4` is coming from, but value isn't null at the location of  the error.  So something weird is happening.
