### ISSUE TITLE
All classes in the JDK with size() methods need to be annotated

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#114]
All/most `size()` methods in the JDK should be annotated as returning `@NonNegative`.

Then, code like
```java
new int[someList.size()]
```
will typecheck without a `array.length.negative` error.

**Comment by kelloggm** [comment]
All `size()` methods _should_ be annotated like this. I believe every public method that is not in an inner class in the index JDK is annotated as `@NonNegative`. Is there a specific example that's incorrect? Was I wrong in thinking that inner classes don't need to be annotated?

**Comment by mernst** [comment]
Upon closer inspection, I realize that I'm seeing these warnings from classes that are not in the JDK, such as `Map`.  It still comes up a fair amount, but not for lists.

**Comment by kelloggm** [comment]
So `Map` needs to be added to the annotated JDK? I can definitely do that; are there any other classes that are problematic?

**Comment by mernst** [comment]
Also `Set`.  And subclasses of those.
