### ISSUE TITLE
Non-negative plus positive is positive, but MinLen can't use that information

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#117]
Typechecking this code:

```java
public class Index117 {

  public static void foo(boolean includeIndex, String[] roots) {

    String[] result = new String[(includeIndex ? 2 : 1) * roots.length + 2];
    result[0] = "hello";

    String[] result2 = new String[2 * roots.length + 2];
    result2[0] = "hello";

    String[] result3 = new String[roots.length + 2];
    result3[0] = "hello";

    String[] result4 = new String[0 + 2];
    result4[0] = "hello";

  }

}
```

leads to the following errors; only the last array assignment is permitted.

```
% $ch/bin/javac -processor index -g Index117.java
Index117.java:6: error: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
    result[0] = "hello";
           ^
  found   : @UpperBoundUnknown int
  required: an integer less than result's length (@LTLengthOf("result"))
Index117.java:9: error: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
    result2[0] = "hello";
            ^
  found   : @UpperBoundUnknown int
  required: an integer less than result2's length (@LTLengthOf("result2"))
Index117.java:12: error: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
    result3[0] = "hello";
            ^
  found   : @UpperBoundUnknown int
  required: an integer less than result3's length (@LTLengthOf("result3"))
3 errors
```

**Comment by smillst** [comment]
The title of this issue refers to the Lower Bound Checker annotations, but the error is coming from the Upper Bound Checker.  I'm not sure why these errors imply that a nonnegative plus a positive is not a positive.  I can take a guess: If the MinLen Checker could use the Lower Bound annotations, then I would expect this code to type check.  So, it's possible that this is a duplication of #66.

**Comment by kelloggm** [comment]
I agree, this is a duplication of #66. I think we should discuss whether to change the dependency order or to find some other way to get around this problem (run the MinLen Checker twice somehow?)

**Comment by kelloggm** [comment]
Mike and I discussed a possible solution to both this and #66:

We could build an additional checker that handles exactly the case described in #66, but which otherwise uses the MinLen type system. This checker would depend on the Lower Bound Checker and run between the LBC and the UBC. The UBC would then depend on the new checker instead of the existing MinLen checker (but the types would propagate via the LBC). This has the advantage of being a straightforward solution, but introduces a (weird) new checker that does exactly one small thing, which is bad for code quality.

**Comment by smillst** [comment]
I think the proposal above (https://github.com/kelloggm/checker-framework/issues/117#issuecomment-285215055) is a good, hopefully temporary, solution to this problem.  Once `@IntRange` is complete it will be easy to just remove this new checker.

**Comment by kelloggm** [comment]
Any suggestions for a name for the new checker? Right now I'm just calling it "MinLenChecker2" but that doesn't seem like it's a good plan long term.

**Comment by smillst** [comment]
LowerBoundMinLen Checker
NewArrayMinLen Checker
MinLenNewArray Checker

**Comment by mernst** [comment]
I vote for `MinLenNewArray` or maybe `MinLenFromNewArray`.

**Comment by kelloggm** [comment]
I've implemented a (mostly) correct version of this new checker, but there is still a problem that I really should have foreseen. Consider the following code:

```java
    void test2(@Positive int a) {
	int @MinLen(1) [] b = new int[a];
    }
```
Although the new checker accepts this, the old MinLen Checker still runs first, and issues an error. I'm not really sure how we could get around this other than forcing the user to suppress the warning, which is what we wanted to avoid in the first place. I'd appreciate input from y'all.

**Comment by kelloggm** [comment]
MinLen annotations can now be inferred from Positive annotations written explicitly by the programmer. However, there is no such annotation here, so this issue remains open. The fundamental thing that's going on here is that the code is relying arithmetic operations on `roots.length` to not result in an overflow. As it stands, the Value Checker assumes that overflow could occur, so this code cannot be typechecked (`roots.length + 2` might overflow). 

Running the Value Checker in no-overflow mode would allow this code to typecheck (see typetools#1233). Once that PR is merged, I will add this code to its test suite and close this issue; I think that the code only verifying when the no-overflow assumption is made explicit is the appropriate behavior from the checker.
