### ISSUE TITLE
Test against constant and constant-length array

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#118]
Consider this code:

```java
import org.checkerframework.checker.index.qual.NonNegative;
import org.checkerframework.common.value.qual.ArrayLen;

public class Index118 {

  public static void foo(String @ArrayLen(4)[] args) {
    for (int i = 1; i <= 3; i++) {
      System.out.println(args[i]);
    }
  }

  public static void bar(@NonNegative int i, String @ArrayLen(4)[] args) {
    if (i <= 3) {
      System.out.println(args[i]);
    }
  }

}
```

The index operations look good to me, but the Index Checker issues errors:
```
Index118.java:8: error: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
      System.out.println(args[i]);
                              ^
  found   : @UpperBoundUnknown int
  required: an integer less than args's length (@LTLengthOf("args"))
Index118.java:14: error: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
      System.out.println(args[i]);
                              ^
  found   : @UpperBoundUnknown int
  required: an integer less than args's length (@LTLengthOf("args"))
2 errors
```

**Comment by kelloggm** [comment]
This is duplicate with #14. This is an issue we've had for a very long time (obviously). We've never done what is strictly necessary to "fix" it, which would be to check every minlen annotation in the store every time a constant integer is introduced. Right now, we instead only make that check when either a constant is used as an index or when it is assigned into another variable (i.e. the common assignment check). That means that we don't do dataflow refinements on constants.

**Comment by smillst** [comment]
An alternative to what @kelloggm  suggests above is to use the `@IntRange` enhancement to the Const. Value Checker (see PR typetools/checker-framework#994).  In this example, the type of `i` would be `@IntRange(from=0, to=3)` which is a valid index of `args`.

**Comment by kelloggm** [comment]
We've mentioned doing that before, as well. When can we expect that PR to be merged?

**Comment by mernst** [comment]
The PR is going slowly, but Jason is making progress.  As of today, I am happy with the class that implements all the transfer-function logic.  So that is one class down, and certainly the most complicated one.  I don't think we should delay waiting for that pull request, but I agree that it can improve the functionality of the Index Checker when it is done.

**Comment by mernst** [comment]
A comment above says, "This is duplicate with #14.", but #14 is now closed.  What is the status of this issue?
