### ISSUE TITLE
An array created with @Positive length should be @MinLen(1)

### ISSUE THREAD

**Issue by jashug** [kelloggm/checker-framework#125]
The following code does not type-check, but if an array is created with len positive, then len >= 1 so the return value with have .length >= 1, so can be typed as MinLen(1).

```
import org.checkerframework.checker.index.qual.*;

class IndexPosLen {
    public int @MinLen(1) [] foo(@Positive int len) {
        return new int[len];
    }
}
```

**Comment by smillst** [comment]
Thanks for reporting!  This is a duplication of #66 and and #117.  I'm closing this issue in favor of those.
