### ISSUE TITLE
@PolyLength syntactic sugar

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#128]
`@PolyValue` and `@PolySameLen` seem to be used together a lot.  Should there be a `@PolyLength` annotation that stands for both?
The manual should explicitly say how to write a routine that takes an array (or whatever) and returns another one of the same length, because I expect that to be common.

The fact that the Index Checker and the Value Checker support `@PolyAll` makes this less critical, but it may still nice to have an annotation that has smaller scope.  Do we have a concrete use case, beyond the definite benefits of reduced verbosity?

**Comment by kelloggm** [comment]
I think this is a good idea.

**Comment by mernst** [comment]
Also probably `@PolyArrayLen`

**Comment by kelloggm** [comment]
Closed by typetools #1349
