### ISSUE TITLE
@SameLen with an offset

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#132]
Once issue #131 is resolved, the following code will type-check:

```java
import org.checkerframework.common.value.qual.ArrayLen;

public class SameLenOffset {
  public static String /*@ArrayLen({3,4})*/[] esc_quantify(String /*@ArrayLen({1,2})*/... vars) {
    if (vars.length == 1) {
      return new String[] {"hello", vars[0], ")"};
    } else {
      return new String[] {"hello", vars[0], vars[1], ")"};
    }
  }
}
```

However, I would like to write a more precise specification:  that the output array has length 2 greater than the input array.  Adding an offset to `@SameLen` would permit that, but perhaps there are other ways to achieve the same effect.  In my application, clients pass in an array of known length (1 or 2) and use legal indices on the returned array, but the Index Checker cannot verify this code.

**Comment by kelloggm** [comment]
Closed in favor of #158
