### ISSUE TITLE
Coalesce Index Checker reports by line

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#148]
The output of the Index Checker exposes that its subcheckers are run one-by-one.

Suppose there is a call on line 10:  `needsIndexFor(someArg)`.

The Index Checker will first report that, on line 10, `someArg` needs to be `@NonNegative`.
Then, after reporting all the errors about all the other lines of code, the Index Checker will report that `someArg` needs to be `@LTLengthOf`.

This forces users to page in the code twice -- once for each error message.

Ideally, I would like the Index Checker to report, at line 10, than `someArg` needs to be `@IndexFor`.  This would be most natural and useful.

Alternately, the Index Checker could sort its output by line number and report the two issues with a given expression near one another.

**Comment by kelloggm** [comment]
I think this will be addressed by replacing the Lower Bound Checker with the Value Checker. The UBC will then do all of the reporting that the LBC currently does, so both the lowerbound and upperbound warnings will be issued at the same place. It should be straightforward to modify the UB Visitor to issue only one warning when both would be issued, as well, once this change is made.

**Comment by smillst** [comment]
That will fix the problem with array access too high and too low warnings.  But normal type checking errors will still be reported separately. PR
https://github.com/typetools/checker-framework/pull/1234 implements the sort error messages solution.

**Comment by smillst** [comment]
Only going to sort error message.  (Merged 0c2c4f822778859f82002a1d5f8fa1e3b90b2e91)
