### ISSUE TITLE
Upperbound LUB is wrong

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#15]
It should be set intersection when the two types are the same ignoring values. It's currently set union.

Consider this code (thanks Mike):

if (cond) then x = a.length else x = b.length fi

after the fi, the UBC currently gives x type LTEL(a,b). It should be unknown.

**Comment by kelloggm** [comment]
Fixed by 7ec5d3041e4179f6646c41c633acb4f9d75a51c9

**Comment by jsantino** [comment]
Didn't update documentation

**Comment by kelloggm** [comment]
Fixed in c6f2abb7e5fb0d97e4a9b558a1ceaf849dd912ec
