### ISSUE TITLE
@LengthOf annotation

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#151]
I would like to revisit the possibility of a `@LengthOf` annotation.

We discussed this before and concluded that `@LengthOf` does not provide any additional information that would prevent false positive warnings.

However, annotations serve another purpose beyond improving type-checker precision:  annotations act as documentation that is written and read by programmers.

When using the Index Checker, I find it irritating to have to write `@IndexOrHigh("arr")` when I know that the value is exactly the length of array arr.  When reviewing annotated code, I am taken aback by the `@IndexOrHigh` annotation, until I realize that the annotation is imprecise and the value is never `@IndexFor`, only equal to the length.

Therefore, as a user I would like to have a `@LengthOf` annotation, even if it does not improve the type-checker's output.

**Comment by kelloggm** [comment]
I intend to create an `@LengthOf` annotation and alias it to `@IndexOrHigh`. This obviously doesn't improve precision, but it still is beneficial for the reasons Mike described above. We can improve precision based on it later.

**Comment by mernst** [comment]
This is now partially completed by PR typetools/checker-framework#1225, which introduced `@LengthOf`.
This issue remains open:  in the future, we would like to give `@LengthOf` more precise semantics.

**Comment by mernst** [comment]
Closing, because this does not specify what "more precise semantics" to give to `@LengthOf`.  If we have specifics in the future, we can create a new issue then.
