### ISSUE TITLE
Index checker requires returning PolySameLen when overriding clone()

### ISSUE THREAD

**Issue by panacekcz** [kelloggm/checker-framework#164]
In the index JDK, `Object.clone` is annotated [`@PolySameLen Object clone(@PolySameLen Object this)`](https://github.com/typetools/checker-framework/blob/4e53646b1e4ab76b378797abed562933a230a300/checker/jdk/index/src/java/lang/Object.java#L214). This causes a warning about incompatible return type (missing `@PolySameLen`) when overriding this method.
This would make sense for fixed size collections (implementers should guarantee that the cloned collection has the same size). However, for non-collection types, `@PolySameLen` does not make sense and the only solution is to suppress the warning.

Minimized test case:
```java
class Cloning implements Cloneable{
	@Override
	protected Cloning clone() throws CloneNotSupportedException {
		return new Cloning();
	}
}
```
Ouput of the index checker:
```
Cloning.java:3: error: [override.return.invalid] Incompatible return type.
	protected Cloning clone() throws CloneNotSupportedException {
	          ^
  Method
    @SameLenUnknown Cloning clone(@SameLenUnknown Cloning this) throws @SameLenUnknown CloneNotSupportedException in Cloning
    cannot override
    @PolySameLen Object clone(@PolySameLen Object this) throws @SameLenUnknown CloneNotSupportedException in java.lang.Object
  found   : @SameLenUnknown Cloning
  required: @PolySameLen Object
```

This showed up when running the index checker on plume-lib, in [LimitedSizeIntSet.java](https://github.com/mernst/plume-lib-check-index-new/blob/3f82f73faaf4c01bee92944a1ea16d8e854bf2fb/java/src/plume/LimitedSizeIntSet.java#L177):
```
src/plume/LimitedSizeIntSet.java:177: warning: [override.return.invalid] Incompatible return type.
  public LimitedSizeIntSet clone(/*>>>@GuardSatisfied LimitedSizeIntSet this*/) {
         ^
  Method
    @SameLenUnknown LimitedSizeIntSet clone(@SameLenUnknown LimitedSizeIntSet this) in plume.LimitedSizeIntSet
    cannot override
    @PolySameLen Object clone(@PolySameLen Object this) throws @SameLenUnknown CloneNotSupportedException in java.lang.Object
  found   : @SameLenUnknown LimitedSizeIntSet
  required: @PolySameLen Object
```

Related: typetools#1320, #146

**Comment by kelloggm** [comment]
Fixed by #1577
