### ISSUE TITLE
endsWith and subtraction

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#168]
After calling endsWith string, the position of the given tested suffix should be `@IndexOrHigh`.  This is a common use case.  The below test case is committed as 
checker/tests/index/EndsWith2.java

This is probably related to https://github.com/kelloggm/checker-framework/issues/56 which is closed but didn't have test cases that used the indices.

```java
// Test case for issue #168: https://github.com/kelloggm/checker-framework/issues/168

// @skip-test until the issue is fixed

public class EndsWith2 {

    public static String invertBrackets(String classname) {

        // Get the array depth (if any)
        int array_depth = 0;
        String brackets = "";
        while (classname.endsWith("[]")) {
            brackets = brackets + classname.substring(classname.length() - 2);
            classname = classname.substring(0, classname.length() - 2);
            array_depth++;
        }
        return brackets + classname;
    }
}
```

**Comment by panacekcz** [comment]
This use case is supported by typetools#1432 (which closed #56) but fails because of typetools#1423 (the `array_depth` variable causes widening of the length range of `classname`).
