### ISSUE TITLE
UBQualifier error messages are not good

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#173]
If one writes an upperbound annotation without an argument, a reasonable error should be thrown that indicates where the problem is. Currently, the Index Checker crashes with a failed assertion in UBQualifier instead. This isn't helpful, since it doesn't help find the problem.

For instance, code like this:
```java
void do_something(@IndexOrHigh int x, String s) { ... }
```
should issue a warning about an invalid annotation at a particular location instead of crashing.

**Comment by smillst** [comment]
You just need to change the declaration of IndexOrHigh to not supply a default value:

Change this:
```
    String[] value() default {};
```

To that:
```
    String[] value();
```

**Comment by kelloggm** [comment]
Thanks, good idea.

On Mon, Oct 9, 2017 at 10:58 AM, Suzanne Millstein <notifications@github.com
