### ISSUE TITLE
Imprecise IndexFor annotations on JDK methods taking a range

### ISSUE THREAD

**Issue by panacekcz** [kelloggm/checker-framework#191]
As mentioned in panacekcz#5, methods that take an array and a range of indices, often have the start of the range annotated by `@IndexFor`. However, a `@IndexOrHigh` annotation would be more precise, because the range might be an empty range at the end of the array.

A common example, where this leads to false positives, is passing 0 as the start index, where the array might be empty. For example, if we have an overload that takes just an array and the range is the whole array:
```java
import org.checkerframework.checker.index.qual.IndexFor;
import org.checkerframework.checker.index.qual.IndexOrHigh;

public class IndexRange {
	
	public void m(Object[] a) {
		m(a, 0, a.length); // line 7
	}
	public void m(Object[] a, @IndexFor("#1") int start, @IndexOrHigh("#1") int end) {
		
	}
}
```
Output:
```
IndexRange.java:7: error: [argument.type.incompatible] incompatible types in argument.
		m(a, 0, a.length);
		     ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf(value="a", offset={}) int
1 error
```
If we change `@IndexFor` to `@IndexOrHigh`, no warning is produced.

Some of those annotations were changed in typetools#1577. Do we want to change all the other occurences?

**Comment by mernst** [comment]
Yes, I think we want to update library annotations anytime that we find that they are incorrect.

`@IndexOrHigh` is correct if 0 is always a legal index.  If 0 is sometimes an illegal index, then the annotation would lead to false negatives (failure to warn when the indices are illegal) and we would want to find another solution.

**Comment by kelloggm** [comment]
We've discussed this issue before, as @panacekcz mentioned. I agree that this change should be applied everywhere. The reasoning is that these methods will never use the value if the array is empty (they exit before attempting to index the array). So, we can relax the contract.

Technically, this does introduce a possible false negative: if `array.length` is passed as this value, we may accept it if the annotation is `@IndexOrHigh`. I'd have to look through the method definitions to make sure they guard against this before indexing, but so long as they do this change should be made everywhere.
