### ISSUE TITLE
UBC fails at something simple

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#21]
From the pilot study:

UBC fails to correctly type this:

for (int i = 0; i < arr.length && i < arr2.length; i++){
   arr[i] = arr2[i];
}

**Comment by kelloggm** [comment]
The problem seems to occur because we don't handle "&&" gracefully. If I switch the order of the "i < x.length" statements in the AND, the warning changes from being about the second access (i.e. the type is LTL(arr), so arr2[i] is illegal) to being about the first access (the type is LTL(arr2), so arr[i] is illegal. Not sure how to deal with this, because these types are coming from the transfer function. I expected that the CF itself would take care of this, but maybe there's something I'm missing?

**Comment by kelloggm** [comment]
Added a test for this (suppressed) in 7d550b5ca3111d6f6a4cfb691b62c1f897f25310

**Comment by smillst** [comment]
The type of `i` after `i < arr2.length` should be `@LTL({"arr","arr2"})`.  Currently, the code tries to refine the type if `i` to `@LTL("arr2")`, which is not more specific than the previous value of `@LTL("arr")`.  So, the transfer function needs to take the GLB of the previous value and the new value and insert the GLB in the store.

**Comment by kelloggm** [comment]
Fixed with c938340919a89eba879e671145fdfab5b47a1d54
