### ISSUE TITLE
Inferring positive and less than annotations after != test

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#228]
Given `a : @NonNegative @LessThan("b + 1")` and `b : @NonNegative`, if `a` is not equal to `b`, then `b` is `@Positive` and `a` is `@LessThan("b")`. Example from Guava (8+ false positives):

```    
   public List<Short> subList(
            @IndexOrHigh("this") @LessThan("#2 + 1") int fromIndex,
            @IndexOrHigh("this") int toIndex) {
        int size = size();
        if (fromIndex == toIndex) {
            return Collections.emptyList();
        }
        return new ShortArrayAsList(array, start + fromIndex, start + toIndex);
    }
```
In the example above, `fromIndex` is `a` and `toIndex` is `b`. `start + toIndex` must be `@Positive` for the call to the constructor on the last line to typecheck.

**Comment by smillst** [comment]
The LessThan Checker can't use `@NonNeg` and `@Positive` because the Lower Bound Checker uses `@LessThan`.  But is it needed?  

If `a < b + 1` and `a != b` then is `a < b`?

**Comment by kelloggm** [comment]
> If `a < b + 1` and `a != b` then is `a < b`?

Good point. For Guava, I'm more interested in the lower bound fact (i.e. that it's positive), but we should probably just implement that in general.

**Comment by smillst** [comment]
I'm working on this.
