### ISSUE TITLE
Incomplete renaming of LessThanLength

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#32]
File `checker-framework/checker/manual/upperbound.svg` still uses the old name `@LessThanLength`.

**Comment by mernst** [comment]
Also, the diagram is incorrect:  `@LTEqLengthOf` should be a supertype, not a subtype, of `@LTLengthOf`.

**Comment by kelloggm** [comment]
Closed in 05154fcf2e8fbc4491c9a8dc1328bd256eb23e54
