### ISSUE TITLE
Should warn on negative length array creation

### ISSUE THREAD

**Issue by jsantino** [kelloggm/checker-framework#37]
There should be a warning issued if a user tries to instantiate an array with a possibly negative number.

```
import org.checkerframework.checker.lowerbound.qual.*;

// @skip-test until the bug is fixed

public class NegativeArray {

    public static void negativeArray (@GTENegativeOne int len) {
        //:: error: (array.length.negative)
       int [] arr = new int[len];
    }

}
```

Test Case: checker-framework/checker/tests/lowerbound/NegativeArray.java

**Comment by kelloggm** [comment]
Added support for this in 043fca5394b8566fb4689ad9a6ff1174b8f6ad95
