### ISSUE TITLE
Pre Decrememt doesn't warn properly

### ISSUE THREAD

**Issue by jsantino** [kelloggm/checker-framework#39]
predecrement in an array access does not give a warning but should

```
  void pre1(int [] args) {
    int ii = 0;
    while ((ii < args.length)) {
      //:: warning: (array.access.unsafe.high)
      int m = args[++ii];
    }
  }
```

Test Case: checker-framework/checker/tests/upperbound/PreAndPostDec.java

**Comment by kelloggm** [comment]
Fixed in bd29976af08d92d69afe3ddd1567d004cc946238
