### ISSUE TITLE
When an array is created with another array's length + a NonNegative, anything that's LTL of the first array should be LTL of the second:

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#44]
Consider the following code:
```
int[] newArray = new int[firstArray.length + secondArray.length];
for (int i = 0; i < firstArray.length; i++){	
    newArray[i] = firstArray[i]; //or newArray[i] = secondArray[i];
}
```
This access should definitely be legal. This came from a pilot study too.

**Comment by kelloggm** [comment]
Added a test in 817cf431704130d2b97a8a25ab4f032455e44e45

**Comment by kelloggm** [comment]
This is related to #52, and can likely be solved at the same time

**Comment by kelloggm** [comment]
Mike,

I don't believe this property is expressible in the type system as is in the general case. To learn that i is LTL(newArray) in the example above we have to learn that newArray's length is greater than or equal to firstArray's length. We could do this with the SameLen checker using one of my old proposals (for GTE/GT/LT/LTE types between arrays based on their length); is that what you intend for me to implement here. That is a large amount of work for what I think is a rare case; the only place we've seen this code is one pilot study merge sort implementation.

Martin

**Comment by kelloggm** [comment]
@mernst,

I don't believe this property is expressible in the type system as is in the general case. To learn that i is LTL(newArray) in the example above we have to learn that newArray's length is greater than or equal to firstArray's length. We could do this with the SameLen checker using one of my old proposals (for GTE/GT/LT/LTE types between arrays based on their length); is that what you intend for me to implement here. That is a large amount of work for what I think is a rare case; the only place we've seen this code is one pilot study merge sort implementation.

Martin

**Comment by mernst** [comment]
OK, if this is hard to do we can defer it.  I was going by your comment that suggested this was important.

**Comment by mernst** [comment]
Here is a way to infer the needed properties without adding new qualifiers.
After 

```java
int[] newArray = new int[firstArray.length + secondArray.length];
```

the type of `firstArray.length` and `secondArray.length` should both be `@LTEqLengthOf(newarray)`.
You may be able to find a more general rule.

**Comment by kelloggm** [comment]
Closed with ebf1c93f82cb869a029d9284e9c301a78c1b3be1

**Comment by smillst** [comment]
This issue is not fixed until the code changes are submitted as a pull request to typetools/master and then merged.  So, I'm going to re-open.

**Comment by kelloggm** [comment]
A PR for this is open

**Comment by kelloggm** [comment]
This was merged several days ago.

**Comment by kelloggm** [comment]
Solution on branch "typetools"

Blocked on https://github.com/typetools/checker-framework/pull/1031

**Comment by kelloggm** [comment]
Opened a PR: typetools#1060

**Comment by kelloggm** [comment]
typetools#1060 has been merged
