### ISSUE TITLE
Two arrays whose length differs by a known amount; one is accessed with an offset

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#50]
We currently don't have a way to deal with offsets. This is a pretty common pattern for accessing arrays, and it almost always results in warnings from the UBC, and sometimes even from the LBC, as well. 

I should think a bit about how we might be able to handle offsets in a way that's clean and doesn't require the user to be suppressing warnings all the time.

**Comment by kelloggm** [comment]
We could maybe handle this with SameLen("a", offset="expr")

**Comment by mernst** [comment]
This is blocked by issue #49 (or maybe they will be resolved together).

**Comment by kelloggm** [comment]
This issue was very unclear. It's now been split into three issues, which each represent a different instance of the general problem. This issue is being maintained as what I've been regarding as the canonical version of this problem:

```java
T[] result = (T[]) new /*@MonotonicNonNull*/ Object[a.length + b.size()];

        System.arraycopy(a, 0, result, 0, a.length);
        // System.arraycopy(b, 0, result, a.length, b.size());
        for (int i = 0; i < b.size(); i++) {
          result[i + a.length] = b.get(i); // index TODO: issue #50
        }
```

**Comment by smillst** [comment]
Fixed via https://github.com/typetools/checker-framework/commit/4c3163a48582f8837fdbfe1176043a273e378ddf
