### ISSUE TITLE
Checker doesn't learn information about subexpressions

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#52]
Consider:

```
public void test(int[] b){
	int [] a = new int[b.length + 1];
	a[b.length] = 5;
    }
```
You and I know that b.length is less than a.length, but the checker doesn't learn that fact right now.

**Comment by kelloggm** [comment]
This is related to #44 and can likely be solved at the same time

**Comment by smillst** [comment]
The UBC now learns some information about sub-expressions, including the example in this issue.  We may wish to add more information about more sub-expressions in the future.
Fixed via https://github.com/typetools/checker-framework/commit/4c3163a48582f8837fdbfe1176043a273e378ddf
