### ISSUE TITLE
Annotation to indicate a subarray (offset vs. length)

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#53]
There are two different ways that a routine may indicate a subarray:
 * take as arguments two indexes into the array (start index and end index)
 * take as arguments a start index (sometimes called an offset) into the array, and a length of the subarray

It would be nice to have a way to indicate the latter pattern, such as indicating that `startIndex + len` is an index for an array.  The len variable could be annotated as something like `@IndexFor("a", offset="startIndex")`.

Here is a real bug in plume-lib that indicates that programmers mix this up:

```java
  /**
   * Write a portion of a string.
   *
   * @param s string to be printed
   * @param off offset from which to start writing characters
   * @param len number of characters to write
   */
  public void write(String s, int off, int len) {
    writtenBytes += countBytes(s.substring(off, len)); // "len" should be "off+len"
    writtenChars += len;
    super.write(s, off, len);
  }
```

**Comment by smillst** [comment]
Keep in mind that a value can be an index for multiple arrays. 

Is the following legal? Does it mean that `len` is an offset for both `array1` and `array2` or just `array1`? 
 `@IndexFor(value = {"array1", "array2"} offset = "len")`  

What about this annotation? Does it mean that `len1` is an offset for both `array1` and `array2` or just `array1`? 
 `@IndexFor(value = {"array1", "array2"} offset = {"len1", "len2")`

**Comment by mernst** [comment]
The current plan is that
`@IndexFor(value = {"array1", "array2"}, offset = "len")`
is legal and means an index into both arrays at the same offset.  (We might want to rename this annotation to `@IndexForOffset` or `@IndexForWithOffset` so that `@IndexFor` remains shorter to write and read.)

The current plan is that
`@IndexFor(value = {"array1", "array2"}, offset = {"len1", "len2")`
is not legal.  This reduces expressiveness, but I suspect that relationships among 3 arrays are rarer than those among 2 arrays.  Experimentation will indicate whether this reduced expressiveness is acceptable.  If it's unacceptable, then we can make `@IndexForWithOffset` a repeatable annotation.

**Comment by smillst** [comment]
>If it's unacceptable, then we can make @IndexForWithOffset a repeatable annotation.

FYI, the Checker Framework does not support repeated annotations as qualifiers, but I'm sure we can figure out some other way to express this.

**Comment by mernst** [comment]
OK, then we can require the value and offset arrays to be the same length, and 
`@IndexFor(value = {"array1", "array2"}, offset = {"len1", "len2"})`
would mean the same as the repeated annotation
`@IndexFor(value = "array1", offset = "len1")  @IndexFor(value = "array2", offset = "len2")`
We'll see if this is necessary, though.

**Comment by smillst** [comment]
Fixed via https://github.com/typetools/checker-framework/commit/4c3163a48582f8837fdbfe1176043a273e378ddf
