### ISSUE TITLE
@MinLen for literal string

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#55]
A literal string should be assigned a `@MinLen` annotation equal to its length.

See the test case in
`checker-framework/checker/tests/minlen/LiteralString.java`

**Comment by jsantino** [comment]
This functionality should be added in the VisitLiteral method in the MinLenAnnotatedTypeFactory.

**Comment by kelloggm** [comment]
Fixed in 5943aeb889076017c4e4b6f9cb16289be9b3a29a
