### ISSUE TITLE
Test against s.length should refine the tested length to @IndexFor("s")

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#59]
Here is a test case:

```java
  public static String lpad(String s, int length) {
    if (s.length() < length) {
      // unimportant code
    } else {
      return s.substring(0, length);
    }
  }
```

The checker issues this warning:

```
warning: [argument.type.incompatible] incompatible types in argument.
      return s.substring(0, length);
                            ^
  found   : @LowerBoundUnknown int
  required: @NonNegative int
```

**Comment by jsantino** [comment]
This is a correct warning:
the else branch ensures this fact:
`s.length() >= length` or equivalently `length <= s.length()`
Therefore in the else branch length could be negative
annotating the parameter to be `@NonNegative int length` should avoid this error.

**Comment by mernst** [comment]
You are right that the behavior is correct on the code I provided.  Thanks for catching my goof.  I have created a new issue, #68, with a proper test case for the issue.
