### ISSUE TITLE
JDK annotation: PrintWriter.write

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#61]
The last two parameters of [`PrintWriter.write(String, int, int)`](https://docs.oracle.com/javase/8/docs/api/java/io/PrintWriter.html#write-java.lang.String-int-int-) should be annotated as `/*@IndexFor("#1")*/`; it may be worthwhile to look for other parametrs named `off` and `len`, too.

**Comment by mernst** [comment]
Blocked on #74

**Comment by kelloggm** [comment]
This was fixed by https://github.com/typetools/checker-framework/pull/1034
