### ISSUE TITLE
JDK annotations: StringBuilder

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#63]
In `StringBuilder.append(CharSequence, int, int)`, the `start` and `end` parameters should be annotated as `@IndexFor("#1")`.  Likewise for `subSequence`.

For `charAt`'s `index` parameter, the annotation should be `@IndexFor("this")`.
Likewise for `length`'s return value.

Probably likewise for many other variables named `start`, `end`, and `index`.
And for other methods with the same names as these.

**Comment by mernst** [comment]
Blocked on #74

**Comment by kelloggm** [comment]
Blocked on #80

**Comment by kelloggm** [comment]
StringBuilder has annotations in the new annotated JDK included in https://github.com/typetools/checker-framework/pull/1034. They are commented out, but I'm closing this issue.
