### ISSUE TITLE
Annotations should apply to primitive wrappers

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#65]
The type-checker should permit annotations to be written on `Integer` as well as `int`, and likewise for other primitive wrappers.

**Comment by kelloggm** [comment]
Do you remember what specific problem you were having here? I've written a simple test case, and it seems that one can write annotations on both `Integer` and `int` and have the same behavior. Here's the test case (which succeeds with no warnings):

```java
    void int_Integer_access_equivalent(@IndexFor("#3") Integer i, @IndexFor("#3") int j, int[] a) {
	a[i] = a[j];
    }

    void array_creation(@NonNegative Integer i, @NonNegative int j) {
	int[] a = new int[j];
	int[] b = new int[i];
    }
```

**Comment by kelloggm** [comment]
If there's nothing more specific to look for I'm going to send a PR to add that test to the index test suite and close this issue.

**Comment by kelloggm** [comment]
typetools#1047 contains a test that shows this works correctly
