### ISSUE TITLE
Array creation expression's @MinLen type should depend on lower bound annotations on size expression

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#66]
The following test is committed as file `checker/tests/minlen/ArrayConstructionPositiveLength.java`:

```java
import org.checkerframework.checker.lowerbound.qual.Positive;
import org.checkerframework.checker.minlen.qual.MinLen;

public class ArrayConstructionPositiveLength {

    public void makeArray(/*@Positive*/ int max_values) {
        String @MinLen(1) [] a = new String[max_values];
    }
}
```

The MinLen Checker issues this spurious warning:
```
ArrayConstructionPositiveLength.java:7: error: [assignment.type.incompatible] incompatible types in assignment.
        String @MinLen(1) [] a = new String[max_values];
                                 ^
  found   : @MinLen(0) String @MinLen(0) []
  required: @MinLen(0) String @MinLen(1) []
1 error
```

**Comment by kelloggm** [comment]
I'd love to do this, but it seems problematic since MinLen is run as a subchecker of the LBC. How can MinLen then use LBC annotations?

**Comment by smillst** [comment]
I think this can be done using the `@IntRange` enhancement to the Const. Value checker. (See https://github.com/typetools/checker-framework/pull/994)

In the Const. Value Checker, alias `@Postive` to `@IntRange(from = 1, to = MAX)`, `@NonNegative` to  `@IntRange(from = 0, to = MAX)` and `@GTENegOne` to  `@IntRange(from = -1, to = MAX)`.  Then update the MinLen Checker to use the `@IntRange` for any array dimension.

Also, if the array demission expression `a.length` op const, then the `@MinLen` of the created array is the min len of "a" plus or minus the constant.  (This is not currently implemented, but should be.)

**Comment by kelloggm** [comment]
The following code pattern occurs throughout ArraysMDE in plume-lib:

```java
  public static byte[] subarray(
      byte[] a, /*@IndexFor("#1")*/ int startindex, /*@IndexOrHigh("#1")*/ int length) {
    byte[] result = new byte[length];
    System.arraycopy(a, startindex, result, 0, length);
    return result;
  }
```

The index checker always warns about the `0` in `System.arraycopy`, because the expected type there is `@IndexFor("result")`, since it will be used as the start index for copying the elements into the destination array. That annotation in the JDK is correct, I think. I'd like to be able to write that the array is `@MinLen(1)`. I'm not sure how I can enforce that without allowing the minlen checker to query the LBC, and annotating `length` as `@Positive`.

**Comment by mernst** [comment]
We decided that we should add a `@IndexOrZero("someArray")` annotation, which should expand to `@NonNegative @LTLengthOrZero("someArray")`.  `@LTLengthOrZero` can be added to the Upper Bound Checker type hierarchy.
