### ISSUE TITLE
Infer ArrayLen for literal array

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#67]
The following test is checked in as file `checker/tests/upperbound/LiteralArray.java`.

```java
import org.checkerframework.checker.index.qual.IndexFor;

public class LiteralArray {

  private static final String[] timeFormat = {
    ("#.#"),
    ("#.#"),
    ("#.#"),
    ("#.#"),
    ("#.#"),
  };

  public String format() {
    return format(1);
  }

  public String format(/*@IndexFor("LiteralArray.timeFormat")*/ int digits) {
    return "";
  }
}
```

The checker issues this error:

```
LiteralArray.java:14: error: [argument.type.incompatible] incompatible types in argument.
    return format(1);
                  ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf("LiteralArray.timeFormat") int
1 error
```

(This should perhaps be fixed in the main repository; but here will be OK for now.)

**Comment by smillst** [comment]
The Constant Value Checker correctly infers the length of `timeFormat`.  (I added a test case https://github.com/typetools/checker-framework/commit/edeb37ca7d53c3a2ba0472f5d628e31003f743eb.)  So, the Index Checker must not be using the `@ArrayLen` in this case.

**Comment by kelloggm** [comment]
If this were just a direct access, the IC would get it right now. However, we currently don't handle pseudo-assignments correctly - we only handle the actual accesses. So when that's fixed, this should be fixed.

**Comment by kelloggm** [comment]
typetools#1048 contains the test for this and was merged
