### ISSUE TITLE
Using an offset variable to access an array

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#75]
Consider the following code:

```java
public static boolean isSubarray(
      /*@PolyAll*/ Object[] a, /*@PolyNull*/ Object[] sub, /*@NonNegative*/ int a_offset) {
    int a_len = a.length - a_offset;
    int sub_len = sub.length;
    if (a_len < sub_len) {
      return false;
    }
    for (int i = 0; i < sub_len; i++) {
      if (!Objects.equals(sub[i], a[a_offset + i])) { // UBC warns here
        return false;
      }
    }
    return true;
}
```

This access is safe, but the UBC has a problem.

We want to express

  the type of a_offset+sub_len is @IndexOrHigh("a")

A syntatically clean way to do so (not as a type annotation, but as a method pre-/post-condition) is
`@ExprIsIndexOrHigh(expr="a_offset+sub_len", array="a")`.

A way to do so as a type annotation (that expresses the offset) is
  the type of a_offset is `@IndexOrHighWithOffset(array="a", offset="sub_len")`
or
  the type of sub_len is `@IndexOrHighWithOffset(array="a", offset="a_offset")`

The implementation is likely to be cleaner and more expressive using type annotations, which the Checker Framework is optimized to handle.  But, it's uglier to write and read.

Here are three general approaches we could take:

1. Maintain non-type-annotation facts like the above in the store.  An expression like `i < sub_len` would introduce a new fact such as 
`@ExprIsIndexOrHigh(expr="#3 + #2.length", array="#1")`.

2. Use type annotations.

3. Use non-type-annotations as the visible representation in the source code -- as syntactic sugar for type annotations that are processed internally.  The existence of those type annotations would probably leak through in some error messages unless we did a bunch of work to hide them.  And it might be rarely necessary to write them within method bodies, in those cases when they cannot be inferred.

**Comment by kelloggm** [comment]
We anticipate that implementing the proposal above will also close #50 and #76.

**Comment by smillst** [comment]
You write `sub_length`, but there isn't a variable with that name in the example.  Do you mean `sub_len` or `sub.length`?  (Please edit the description, then just delete this comment so it doesn't clutter the issue.)

**Comment by smillst** [comment]
Fixed via https://github.com/typetools/checker-framework/commit/4c3163a48582f8837fdbfe1176043a273e378ddf
