### ISSUE TITLE
Handle masks and signed shifts in the Lower Bound Checker

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#8]
In the Lower Bound Checker, these should be `@NonNegative`:
- the result of a mask, if the first mask bit not 1
- the result of a mask, if the masked value is `@NonNegative`
- the result of a signed shift, if the shifted value is `@NonNegative`

In addition to more focused tests, please ensure that the following type-checks:

```
  public static String hexEncode(byte[] bytes) {
    StringBuffer s = new StringBuffer(bytes.length * 2);
    for (int i = 0; i < bytes.length; i++) {
      byte b = bytes[i];
      s.append(digits[(b & 0xf0) >> 4]);
      s.append(digits[b & 0x0f]);
    }
    return s.toString();
  }
```

**Comment by kelloggm** [comment]
is "digits" on lines 8 and 9 of this code snippet meant to be "bytes"? If not, should digits be a parameter?

**Comment by mernst** [comment]
Sorry, I omitted a declaration that is needed by the code snippet:

```
  private static final char[] digits = {
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'
  };
```

Here is the actual code:
https://github.com/mernst/plume-lib/blob/master/java/src/plume/Digest.java#L65

**Comment by kelloggm** [comment]
Thanks.

**Comment by kelloggm** [comment]
This was fixed months ago; not sure why the issue is still open. The test case is part of the index test suite.
