### ISSUE TITLE
Integer.MAX_VALUE and similar fields

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#82]
Should probably be @Positive...

**Comment by mernst** [comment]
This is a JDK library annotation issue, right?

**Comment by kelloggm** [comment]
Yes. I added it to remind myself that this is important, because it might be overlooked using a methods-only approach.

**Comment by kelloggm** [comment]
Included in the index-jdk PR https://github.com/typetools/checker-framework/pull/1034
