### ISSUE TITLE
Zero is LTLengthOf empty array

### ISSUE THREAD

**Issue by jashug** [kelloggm/checker-framework#83]
This code issues no warnings under the index checker, and causes an ArrayIndexOutOfBoundsException on line 7 `a[i] = 42;` when run. I expected the index checker to warn about this invalid array access. Line 8 `a[0] = 42;` does give a warning when uncommented, so the index checker is operating.
```
import org.checkerframework.checker.index.qual.*;

class IndexZeroLessThanZero {
    public static void main(String[] args) {
        int [] a = new int[0];
        @LTLengthOf("a") int i = 0;
        a[i] = 42; // ArrayIndexOutOfBoundsException
        //a[0] = 42; // Index checker warning
    }
}
```

I am working with the checker framework version 2.1.8, commit 3c2f654, compiled from source under WSL.
Commands are `javac -processor index IndexZeroLessThanZero.java` to compile and check, and `java IndexZeroLessThanZero` to run. Adding all the soundness flags in the manual still does not produce a warning: `javac -processor index -AcheckPurityAnnotations -AinvariantArrays -AcheckCastElementType -AuseDefaultsForUncheckedCode=source,byte -AconcurrentSemantics IndexZeroLessThanZero.java`

The output of `javac -processor index -version -verbose -AprintErrorStack -AprintAllQualifiers IndexZeroLessThanZero.java` is attached as IndexZeroLessThanZero.txt
[IndexZeroLessThanZero.txt](https://github.com/kelloggm/checker-framework/files/741332/IndexZeroLessThanZero.txt)

**Comment by smillst** [comment]
Thanks for reporting this.  I'm working on adding offsets to `@LTLengthOf` and in the code I corrected this bug.  I'll close this issue once that fix is in typetools/master.

**Comment by smillst** [comment]
Fixed via https://github.com/typetools/checker-framework/commit/4c3163a48582f8837fdbfe1176043a273e378ddf
