### ISSUE TITLE
Adding 2 indexes of an array and dividing by 2

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#86]
consider the following code:
```
import org.checkerframework.checker.index.qual.*;

public class IndexForBug {
	
	public static void bug(int[] a, @IndexFor("#1") int i, @IndexFor("#1") int j) {
		@IndexFor("a") int k = (i + j)/2; //upperbound unknown
	}
} 
```

warning issued by the checker:

IndexForBug.java:6: error: [assignment.type.incompatible] incompatible types in assignment.
		@IndexFor("a") int k = (i + j)/2;	
		                              ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf("a") int
1 error

**Comment by mernst** [comment]
I have added a test case as file `checker/tests/upperbound/IndexForAverage.java`

**Comment by mernst** [comment]
We only need to handle this for n = 2 for now; let's leave the generalization to other n for later.

**Comment by kelloggm** [comment]
I've committed a fix on a branch. Waiting for travis tests to pass, then will submit a PR.

**Comment by kelloggm** [comment]
PR merged
