### ISSUE TITLE
@SameLen issues

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#87]
consider:
```
import org.checkerframework.checker.index.qual.*;

public class SameLenBug {


	public static void bug2() {
		int [] a = {1,2,3,4,5};		
		int @SameLen("a")[ ] b = a;
		// warning does not occur if the for loop
		// is replaced with a line such as
		// @IndexFor("a") int i = 2
        	for( int i = 0; i < a.length; i++ )
            		a[ i ] = b[ i ];// checker warning: @LTLOf("b") reired
	}
}
```

warning produced by the checker (also notice 'required' is spelled wrong in the warning):

SameLenBug.java:9: error: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
            		a[ i ] = b[ i ];// checker warning: @LTLOf("b") reired
            		            ^
  found   : @LTLengthOf("a") int
  required: an integer less than b's length (@LTLengthOf("b"))

**Comment by mernst** [comment]
I cannot reproduce this issue.  I have just checked the following test case into the master branch of typetools/checker-framework, and it passes:

```java
import org.checkerframework.checker.index.qual.*;

public class IndexSameLen {

    public static void bug2() {
        int[] a = {1, 2, 3, 4, 5};
        int @SameLen("a") [] b = a;

        @IndexFor("a") int i = 2;
        a[i] = b[i];

        for (int j = 0; j < a.length; j++) {
            a[j] = b[j];
        }
    }
}
```

What fork and branch are you using?  Have you recently re-compiled the Checker Framework?

Please re-open this issue, or open a new one, if you can reproduce the problem.

**Comment by kelloggm** [comment]
Like #88, the unexpected warning in this test case is emitted by the upperbound checker, so this should be an upperbound test case. When run with the upperbound checker, the unexpected warning appears. I will assign myself to this issue.

**Comment by kelloggm** [comment]
A fix is on the branch samelen-fix. The issue was some blatantly wrong code in UpperBoundAnnotatedTypeFactory, and a missing method is SameLenTypeFactory. Issuing a PR now.
