### ISSUE TITLE
N-ary average of IndexFors

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#89]
Generalization of #86, which only handles the binary case.

**Comment by mernst** [comment]
To help prioritize and manage the set of issues, I wouldn't create speculative ones that we think will serve no purpose, or ones with very low priority.  (The only exception would be if there is some important information that we know now and don't want to have to rediscover in the future.)  If this feature is really important, it will come up in a case study or a user will submit an issue.  If it never comes up, then it isn't important.

**Comment by kelloggm** [comment]
If you insist. I created this issue because I'm currently writing a solution for #86 and I wanted to include a note in the code pointing to this issue and explaining that the solution was only for the binary case.

**Comment by kelloggm** [comment]
That purpose is still served by a closed issue, so I'll leave it.

**Comment by mernst** [comment]
I agree the purpose would be served by a closed issue, but this issue has no content.  It's literally one sentence.  The code comment will be shorter and more comprehensible if it just contains that sentence rather than pointing elsewhere.

**Comment by kelloggm** [comment]
So would it be better to have the code refer to #86 directly, then?

**Comment by mernst** [comment]
Why does the code have to refer to an issue at all?  Pointers to external resources make the code not self-contained.  In general, completed code does not refer to issues in the issue tracker.

**Comment by kelloggm** [comment]
I don't view the code as totally complete, though - it doesn't handle the n-ary case. That's the whole reason I created this issue in the first place; I want there to be an explanation of what the code does and doesn't do, and I don't want to write out everything that's in #86 in comments; that seems extreme.

**Comment by kelloggm** [comment]
I was viewing the code that fixes the n-ary case as a hack so that we can ignore the (rare, presumably) n-ary case, and come back to it if we ever have time.

**Comment by mernst** [comment]
I don't see the point of linking to issue #86.  There isn't any content in issue #86, either, other than:

> if i and j are both `@IndexFor("a")`, then so is (i + j)/2

This is best stated in those few words in the code.  That's much better than a link to an issue that has a lot of other cruft in it and would take a reader much more time to interpret and understand.

There is no need to even mention the three-argument case.  There are *lots* of other expressions that could be `@IndexFor("a")` but the code doesn't handle.  (For example, `i/2 + j/2`.)  It would clutter the code to enumerate any of them, and it would confuse readers to enumerate just a few of them.

**Comment by kelloggm** [comment]
I'll remove the reference in the code. I see your point, and it makes sense.

**Comment by mernst** [comment]
Great.  Thanks!
