### ISSUE TITLE
Manual chapter

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#9]
The Index Checker manual chapter should document the Min Length Checker.
It should also document why MinLen even exists, which is a commonly-asked question.  Do this by showing that there are two different situations when `a[i]` is legal:  when `i` is known to be an index for `a` independent of the length of `a`, and when `i` is actually a compile-time constant but facts are known about the length of `a`, in particular a compile-time bound on its minimum length.

The manual still mentions `@EqualToLength`, which has been removed.

**Comment by kelloggm** [comment]
Manual has been updated to mention the MinLen checker, mention that situation (although not in as much detail as you present it here), and to remove references to @EqualToLength.

**Comment by mernst** [comment]
I don't see a subsection about the MinLen Checker, nor its type system.  The explanation in that section of why it exists should be at least as detailed and comprehensible as what I suggested above.

**Comment by kelloggm** [comment]
Alright, I'll write something more comprehensive. I think the manual in general needs to be expanded a bit, and I'll do that at the same time.

**Comment by mernst** [comment]
Sounds good, thanks.

**Comment by kelloggm** [comment]
I've updated the manual to explain a bit more of what's going on, and also included a MinLen subsection. Good enough to close this issue?

**Comment by mernst** [comment]
I made a number of improvements in commit 8b06e3e2cae3a69e02dcdb751e901fc192c8c2d2.  Please take a look to see what I did.  There are still a number of improvements that need to be made.

Figure 7.1 uses the wrong name for @GTENegativeOne.
That name should be @GteNegativeOne; note capitalization.
Do you want to shorten the name of @LessThanOrEqualToLength also?

Figures 7.1-7.3 use a different style than the rest of the manual.  Did you start from an existing diagram as a template, as suggested in file checker/manual/figures/README?
The captions should say what the different fonts mean, as done elsewhere in the manual.

In the Javadoc for LessThanLength and elsewhere, please use a more specific term than "whatever".  Also be careful about mixing kinds.  A type qualifier applies to a type, but a type doesn't have a value.  An expression has a type, and an expression evaluates to a value.
As another example of vagueness, MinLenBottom should not use "etc.".

Figure 7.3 does not adequately explain the type hierarchy; for example, the section doesn't indicate how different @MinLen() annotations relate to one another.  The other diagrams or sections should also do this; for example, what is the relationship between @LessThanLength({"a"}), @LessThanLength({"b"}), and @LessThanLength({"a", "b"})?  Please don't make readers guess or work it out for themselves.

The description of the MinLen Checker started out with a way it is used rather than starting with what it is, which is more important for understanding it.  Its description of the purpose of the MinLen Checker was abstract and hard to understand.  It didn't have an example.

Throughout the documentation, please indicate that these checkers apply to sequences (including arrays and ordered collections); the current documentation only speaks of arrays.

**Comment by mernst** [comment]
Closing issue, since subsequent iterations have improved the manual.
