### ISSUE TITLE
Incorrect handling of GTE with a LTL

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#93]
consider the code:
```
import org.checkerframework.checker.index.qual.*;

public class ArrayCreationParam {

	public static void m1() {
		int n = 5;
		int[] a = new int[n + 1];
		//Index Checker correctly issues no warning on the lines below
		@LTLengthOf("a") int j = n; 
		@IndexFor("a") int k = n;
		for( int i = 1; i <= n; i++ ) {
			int x = a[i];	//Index Checker issues a warning here
		}
        	
	}
}
```
warning issued by the checker:
ArrayCreationParam.java:12: error: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
			int x = a[i];	//Index Checker issues a warning here
			          ^
  found   : @UpperBoundUnknown int
  required: an integer less than a's length (@LTLengthOf("a"))
1 error

**Comment by kelloggm** [comment]
Suzanne's offset code fixes this problem. I'll add the test case above to the test suite after that's merged.
