### ISSUE TITLE
Index Checker limitation: Subtracting two @IndexFor(s)

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#96]
Consider the code:
```java
import org.checkerframework.checker.index.qual.*;
public class Limitation {
	public static void m3() {
		int[] a = {1,2,3,4,5};
		@IndexFor("a") int j = 1;
		@IndexFor("a") int k = 3;
		if(j >= k) {
			@IndexFor("a") int m = j - k;//checker warning
		}
	}
}
```
Note that if I have an @IndexFor("a") int j and an @IndexFor("a") int k. If j >= k, j-k should still be a valid index for the array 'a'.

Checker Warning:
Limitation.java:27: error: [assignment.type.incompatible] incompatible types in assignment.
			@IndexFor("a") int m = j - k;		
			                         ^
  found   : @LowerBoundUnknown int
  required: @NonNegative int

**Comment by kelloggm** [comment]
This is a limitation of the LBC. A more minimized version of this issue is the following code:

```java
void test(@NonNegative int x, @NonNegative int y) {
    @NonNegative int z;
    if (x <= y) {
        z  = y - x; // LBC can't determine that this is non-negative and will warn.
    }
}
```
I'm not certain how we would even go about addressing this, so it's not going to be addressed right away.

**Comment by mernst** [comment]
Addressing this would require a typechecker that tracks the abstraction "variable `a` is less than variable `b`".  This would be a substantial project, and isn't high priority now.
Let us know if this comes up a lot, but for now you should suppress the warning where it comes up.
