### ISSUE TITLE
Index Checker Limitation: offset case

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#97]
Consider the code:
```
import org.checkerframework.checker.index.qual.*;
public class Limitation {
	public static void m2() {
		int[] a = {1,2,3,4,5};
		@IndexFor("a") int i = 4;
		@IndexFor("a") int j = 4;
		if(j < a.length - i) {
			@IndexFor("a") int k = i + j;	
		}	
	}
}
```
Note that i and j are indices for a, and if j < a.length - i. i + j must be valid index for 'a'.
Checker Warning:
Limitation.java:18: error: [assignment.type.incompatible] incompatible types in assignment.
			@IndexFor("a") int k = i + j;	
			                         ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf("a") int
1 error

**Comment by kelloggm** [comment]
Duplicate with #75. Suzanne is working on fixing this right now; see https://github.com/typetools/checker-framework/pull/1031

**Comment by kelloggm** [comment]
Actually, going to leave this open so that we can verify that Suzanne's work does actually fix this.

**Comment by kelloggm** [comment]
Suzanne's offset changes do fix this problem. On the branch abhishek-tests, I've checked in this test. I'll merge it into master after Suzanne's changes merge.
