### ISSUE TITLE
Incorrect dataflow wrt IndexFor_s

### ISSUE THREAD

**Issue by as56** [kelloggm/checker-framework#98]
Consider the code:
```
import org.checkerframework.checker.index.qual.*;
public class Limitation {
	public static void m4(int[] a, @IndexFor("#1") int i, @IndexFor("#1") int j) {
		int k = i;
		// The checker correctly issues no warning on the if block below
		if (k >= j) {
			@IndexFor("a") int y = k;		
		}
		for (k = i; k >= j; k-=j) {
			@IndexFor("a") int x = k;  // index checker warning		
		}
	
	}
}
```

Note that k in the for loop above always remains within the bounds of array a because it starts at i, which is an IndexFor("a") type, and ends when it is greater than or equal to j which is another @IndexFor("a") type. The problem here is with the decrement statement k-=j, replacing j with any non-negative constant seems to ensure that no warning is issued. So if the checker issues no warning on any non-negative constant in place of j, then it should not issue a warning if the statement is written as i-=j because j being an IndexFor("a") is non-negative.

Checker Warning:
Limitation.java:38: error: [assignment.type.incompatible] incompatible types in assignment.
			@IndexFor("a") int x = k;		
			                       ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf("a") int
1 error

**Comment by kelloggm** [comment]
There is a solution to this on the issue98 branch. Merging/PRing it is blocked by both #44 and Suzanne's offset changes.

**Comment by kelloggm** [comment]
typetools#1068 will fix this when merged

**Comment by kelloggm** [comment]
typetools#1068 was merged
